import i18n from 'i18next'
import { initReactI18next } from 'react-i18next'
import LanguageDetector from 'i18next-browser-languagedetector'

// Translation resources
const resources = {
  en: {
    translation: {
      // App title and tagline
      appName: 'Know My Rights AI',
      tagline: 'Your pocket guide to legal empowerment',
      
      // Navigation
      nav: {
        rights: 'My Rights',
        scripts: 'Scripts',
        record: 'Record',
        share: 'Share'
      },
      
      // Rights card
      rights: {
        title: 'Know Your Rights - {{state}}',
        summary: 'Your Rights Summary',
        whatToDo: 'What TO Do',
        whatNotToDo: 'What NOT to Do',
        keyLaws: 'Key State Laws',
        updated: 'Updated {{date}}',
        viewFullGuide: 'View Full Guide',
        generatedFor: 'Generated for {{state}} • {{language}}'
      },
      
      // Recording
      recording: {
        title: 'Incident Documentation',
        description: 'Securely record and store evidence of interactions with law enforcement',
        audio: 'Audio',
        video: 'Video',
        recording: 'Recording in progress...',
        tapToStop: 'Tap the button again to stop recording',
        complete: 'Recording Complete',
        savedLocally: 'Your {{type}} has been saved locally',
        uploadToIPFS: 'Upload to IPFS',
        saveLocally: 'Save Locally',
        proRequired: 'Pro Required',
        infoText: 'Record audio or video evidence during interactions.',
        infoTextPro: 'Your recordings are encrypted and stored securely on IPFS.',
        infoTextFree: 'Upgrade to Pro for unlimited recording and secure IPFS storage.'
      },
      
      // Scripts
      scripts: {
        title: 'Legal Scripts & Translations',
        description: 'Ready-to-use scripts for common scenarios during police encounters',
        scenarios: {
          trafficStop: 'Traffic Stop',
          streetEncounter: 'Street Encounter',
          homeVisit: 'Home Visit',
          temporaryDetention: 'Temporary Detention',
          vehicleSearch: 'Vehicle Search'
        },
        expand: 'Expand',
        collapse: 'Collapse',
        copy: 'Copy',
        copied: 'Copied!'
      },
      
      // Sharing
      sharing: {
        title: 'Share Legal Knowledge',
        description: 'Help others in your community by sharing important rights information',
        shareViaText: 'Share via Text',
        shareOnSocial: 'Share on Social',
        preview: 'Preview',
        generatedBy: 'Generated by Know My Rights AI'
      },
      
      // Subscription
      subscription: {
        upgradeTitle: 'Upgrade to Pro',
        unlockFeatures: 'Unlock Full Features',
        getUnlimited: 'Get unlimited access to all premium features',
        proPlan: 'Pro Plan',
        perMonth: '/month',
        features: {
          unlimitedRecording: 'Unlimited incident recording',
          ipfsStorage: 'IPFS decentralized storage',
          multiLanguage: 'Multi-language support',
          advancedScripts: 'Advanced legal scripts',
          prioritySupport: 'Priority support'
        },
        subscribeNow: 'Subscribe Now',
        upgradeForPro: 'Upgrade to Pro for advanced features like multi-language support, incident recording, and cloud storage.',
        upgradeForFeatures: 'Upgrade to Pro for unlimited recording and IPFS storage'
      },
      
      // Common
      common: {
        loading: 'Loading...',
        error: 'Error',
        retry: 'Retry',
        cancel: 'Cancel',
        confirm: 'Confirm',
        close: 'Close',
        save: 'Save',
        delete: 'Delete',
        edit: 'Edit',
        back: 'Back',
        next: 'Next',
        previous: 'Previous',
        yes: 'Yes',
        no: 'No',
        ok: 'OK'
      },
      
      // Location
      location: {
        detecting: 'Detecting location...',
        failed: 'Failed to detect location',
        permission: 'Location permission required'
      },
      
      // Errors
      errors: {
        general: 'Something went wrong. Please try again.',
        network: 'Network error. Please check your connection.',
        location: 'Unable to detect your location.',
        recording: 'Recording failed. Please check permissions.',
        upload: 'Upload failed. Please try again.',
        payment: 'Payment failed. Please try again.'
      }
    }
  },
  es: {
    translation: {
      // App title and tagline
      appName: 'Conoce Mis Derechos AI',
      tagline: 'Tu guía de bolsillo para el empoderamiento legal',
      
      // Navigation
      nav: {
        rights: 'Mis Derechos',
        scripts: 'Guiones',
        record: 'Grabar',
        share: 'Compartir'
      },
      
      // Rights card
      rights: {
        title: 'Conoce Tus Derechos - {{state}}',
        summary: 'Resumen de Tus Derechos',
        whatToDo: 'Qué HACER',
        whatNotToDo: 'Qué NO Hacer',
        keyLaws: 'Leyes Estatales Clave',
        updated: 'Actualizado {{date}}',
        viewFullGuide: 'Ver Guía Completa',
        generatedFor: 'Generado para {{state}} • {{language}}'
      },
      
      // Recording
      recording: {
        title: 'Documentación de Incidentes',
        description: 'Graba y almacena de forma segura evidencia de interacciones con las fuerzas del orden',
        audio: 'Audio',
        video: 'Video',
        recording: 'Grabación en progreso...',
        tapToStop: 'Toca el botón nuevamente para detener la grabación',
        complete: 'Grabación Completa',
        savedLocally: 'Tu {{type}} ha sido guardado localmente',
        uploadToIPFS: 'Subir a IPFS',
        saveLocally: 'Guardar Localmente',
        proRequired: 'Pro Requerido',
        infoText: 'Graba evidencia de audio o video durante las interacciones.',
        infoTextPro: 'Tus grabaciones están encriptadas y almacenadas de forma segura en IPFS.',
        infoTextFree: 'Actualiza a Pro para grabación ilimitada y almacenamiento seguro en IPFS.'
      },
      
      // Scripts
      scripts: {
        title: 'Guiones Legales y Traducciones',
        description: 'Guiones listos para usar en escenarios comunes durante encuentros policiales',
        scenarios: {
          trafficStop: 'Parada de Tráfico',
          streetEncounter: 'Encuentro Callejero',
          homeVisit: 'Visita Domiciliaria',
          temporaryDetention: 'Detención Temporal',
          vehicleSearch: 'Registro de Vehículo'
        },
        expand: 'Expandir',
        collapse: 'Contraer',
        copy: 'Copiar',
        copied: '¡Copiado!'
      },
      
      // Sharing
      sharing: {
        title: 'Compartir Conocimiento Legal',
        description: 'Ayuda a otros en tu comunidad compartiendo información importante sobre derechos',
        shareViaText: 'Compartir por Texto',
        shareOnSocial: 'Compartir en Redes',
        preview: 'Vista Previa',
        generatedBy: 'Generado por Conoce Mis Derechos AI'
      },
      
      // Subscription
      subscription: {
        upgradeTitle: 'Actualizar a Pro',
        unlockFeatures: 'Desbloquear Todas las Funciones',
        getUnlimited: 'Obtén acceso ilimitado a todas las funciones premium',
        proPlan: 'Plan Pro',
        perMonth: '/mes',
        features: {
          unlimitedRecording: 'Grabación ilimitada de incidentes',
          ipfsStorage: 'Almacenamiento descentralizado IPFS',
          multiLanguage: 'Soporte multi-idioma',
          advancedScripts: 'Guiones legales avanzados',
          prioritySupport: 'Soporte prioritario'
        },
        subscribeNow: 'Suscribirse Ahora',
        upgradeForPro: 'Actualiza a Pro para funciones avanzadas como soporte multi-idioma, grabación de incidentes y almacenamiento en la nube.',
        upgradeForFeatures: 'Actualiza a Pro para grabación ilimitada y almacenamiento IPFS'
      },
      
      // Common
      common: {
        loading: 'Cargando...',
        error: 'Error',
        retry: 'Reintentar',
        cancel: 'Cancelar',
        confirm: 'Confirmar',
        close: 'Cerrar',
        save: 'Guardar',
        delete: 'Eliminar',
        edit: 'Editar',
        back: 'Atrás',
        next: 'Siguiente',
        previous: 'Anterior',
        yes: 'Sí',
        no: 'No',
        ok: 'OK'
      },
      
      // Location
      location: {
        detecting: 'Detectando ubicación...',
        failed: 'Error al detectar ubicación',
        permission: 'Permiso de ubicación requerido'
      },
      
      // Errors
      errors: {
        general: 'Algo salió mal. Por favor intenta de nuevo.',
        network: 'Error de red. Por favor verifica tu conexión.',
        location: 'No se pudo detectar tu ubicación.',
        recording: 'Error en la grabación. Por favor verifica los permisos.',
        upload: 'Error en la subida. Por favor intenta de nuevo.',
        payment: 'Error en el pago. Por favor intenta de nuevo.'
      }
    }
  }
}

i18n
  .use(LanguageDetector)
  .use(initReactI18next)
  .init({
    resources,
    fallbackLng: 'en',
    debug: false,
    
    interpolation: {
      escapeValue: false
    },
    
    detection: {
      order: ['localStorage', 'navigator', 'htmlTag'],
      caches: ['localStorage']
    }
  })

export default i18n
