name: Deploy to Vercel

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build
        env:
          NODE_OPTIONS: --max-old-space-size=4096
          VITE_APP_NAME: "Know My Rights AI"
          VITE_APP_VERSION: "1.0.0"
          VITE_APP_ENVIRONMENT: "production"
          
      - name: Deploy to Vercel (Production)
        if: (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master') && secrets.VERCEL_TOKEN != ''
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          
      - name: Deploy to Vercel (Preview)
        if: (github.ref != 'refs/heads/main' && github.ref != 'refs/heads/master') && secrets.VERCEL_TOKEN != ''
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-args: '--no-wait'
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          github-comment: true
          github-deployment: false
          
      - name: Build Success Notification
        if: secrets.VERCEL_TOKEN == ''
        run: |
          echo "✅ Build completed successfully!"
          echo "📦 Application built and ready for deployment"
          echo "ℹ️  Vercel deployment skipped (secrets not configured)"
          
      - name: Comment PR with build status
        if: github.event_name == 'pull_request' && secrets.VERCEL_TOKEN == ''
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `✅ **Build Completed Successfully!**
              \n\n📦 The application has been built and is ready for deployment.
              \n\nℹ️ Vercel deployment is not configured for this repository. To enable automatic deployments, add the following secrets to your repository:
              \n- \`VERCEL_TOKEN\`
              \n- \`VERCEL_ORG_ID\`  
              \n- \`VERCEL_PROJECT_ID\`
              \n\nYou can deploy manually by running \`npm run build\` and uploading the \`dist\` folder to your hosting provider.`
            });
